spring:
  application:
    name: netflix-zuul-api-gateway-server

server:
  port: 8765

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost